<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nettgrids"
 *
 * Auto generated by Extension Builder 2017-07-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Netthelp Grids',
    'description' => 'Gridelements from Netthelp.de, based on Extension gridelements and Bootstrap',
    'category' => 'misc',
    'author' => 'Uwe Debacher',
    'author_email' => 'typo3@debacher.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
            'gridelements' => '',

        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
        'psr-4' => [
            'Netthelp\\nettgrids\\ViewHelpers\\' => 'Classes'
        ]
    ],

];
